import type { Metadata } from "next";
import { Inter, Roboto, Jolly_Lodger } from "next/font/google";
import "./globals.css";

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
})

const roboto = Roboto({
  weight: ['400', '500', '700'],
  subsets: ['latin'],
  variable: '--font-roboto',
})

const jolly_lodger = Jolly_Lodger({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-jolly',
})

export const metadata: Metadata = {
  title: "John Syslo",
  description: "Generated by John Syslo",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} ${inter.variable} ${jolly_lodger.variable}`}>{children}</body>
    </html>
  );
}
